### ISSUE TITLE
Problem with alignment on mailing list reg form

### ISSUE THREAD

**Issue by tonycodes** [cssninjaStudio/bulkit#6] opened 2018-05-02 12:54 UTC
The below error happens on Chrome Version 66.0.3359.117 (Official Build) (64-bit)

![screen shot 2018-05-02 at 13 52 12](https://user-images.githubusercontent.com/7568679/39524207-20512ad0-4e10-11e8-939e-6bb53ee212d9.png)

**Comment by cssninjaStudio** [comment] 2018-05-02 13:33
Please try upgrading to  Version 66.0.3359.139 (Official Build) (64 bits) to see if something changes. We currently can't reproduce this bug. Do you have the browser zoom enable, some particular addon ? Do you have a live link where i can see this and inspect it ? The footer image seems to be cut, kind of strange.

**Comment by tonycodes** [comment] 2018-05-03 09:43
Thanks for getting back to me so quick on these, i was wondering how much you would charge to apply this template to this website https://hyper.host, keeping a similar colour scheme etc?

Tony James

**Comment by cssninjaStudio** [comment] 2018-05-08 00:49
Sent you an email

**Comment by cssninjaStudio** [comment] 2018-06-11 01:45
Closing this as undetermined. Feel free to reopen if needed.

**Closed by cssninjaStudio** 2018-06-11 01:45 UTC
Labels: bug, indeterminate
